# This is a basic workflow to help you get started with Actions

name: Build and publish release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install zip
        run: sudo apt-get install zip

      # delete dist folder
      - name: delete dist folder
        run: rm -rf dist

      - name: compile less into css
        run: |
          curl -L -o assets/palette_values.css https://unpkg.com/@catppuccin/palette/css/catppuccin.css
          cat assets/palette_values.css

      # Runs a set of commands using the runners shell
      - name: zip each theme (frappe, latte, macchiato, mocha)
        run: |
          mkdir dist
          for f in frappe latte macchiato mocha; do
            cp README.md $f
            cd $f
            zip -r -j ../dist/$f.zip ./*
            cd ..
          done

      # draft a release then publish the dist as the files
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
